data_sources:
  - name: search
    type: opensearch
    connection:
      host: 127.0.0.1
      port: 9201
      username: admin
      password: admin
  - name: content
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5431
      username: postgres
      password: changeme
      database: postgres
  - name: staging
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5430
      username: postgres
      password: changeme
      database: postgres

metrics:

  search:
    count_search:
      metric_type: document_count
      index: category_tabel
      filter:
        search_query: '{"query" : {"match_all" : {}}}'

  content:
    count_content_hat:
      metric_type: row_count
      table: table_1
      filter:
        sql_query: "category = 'HAT' AND is_valid is True"
    count_content_non_valid:
      metric_type: row_count
      table: table_1
      filter:
        sql_query: "is_valid is False"

  staging:
    count_staging:
      metric_type: row_count
      table: table_2
      filter:
        sql_query: "category = 'OIL' AND is_valid is True"
