data_sources:
  - name: search
    type: opensearch
    connection:
      host: 127.0.0.1
      port: 9201
  - name: content
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5431
      username: postgres
      password: changeme
      database: postgres
  - name: staging
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5430
      username: postgres
      password: changeme
      database: postgres

metrics:
  - name: count_search
    data_source: search
    metric_type: document_count
    properties:
      indices:
        - category_tabel
    filter:
      search_query: '{"query" : {"match_all" : { }}}'
  - name: count_content
    data_source: content
    metric_type: row_count
    properties:
      tables:
        - table_1
    filter:
      sql_query: "category = 'HAT' AND is_valid is True"
  - name: count_staging
    data_source: staging
    metric_type: row_count
    properties:
      tables:
        - table_2
    filter:
      sql_query: "category = 'OIL' AND is_valid is True"
