data_sources:
  - name: search
    type: opensearch
    connection:
      host: 127.0.0.1
      port: 9201
      username: admin
      password: admin
  - name: content
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5431
      username: postgres
      password: postgres
      database: dc_db

metrics:

  search:
    count_document:
      metric_type: document_count
      index: category_tabel
      filters:
        search_query: '{"match_all" : {}}'
    max_price:
      metric_type: max
      index: category_tabel
      field: price
    last_updated:
      metric_type: freshness
      index: category_tabel
      field: last_updated

  content:
    count_content_hat:
      metric_type: row_count
      table: table_1
      filters:
        where_clause: "category = 'HAT' AND is_valid is True"
    count_content_non_valid:
      metric_type: row_count
      table: table_1
      filters:
        where_clause: "is_valid is False"
    max_content:
      metric_type: max
      table: table_1
      field: price
