data_sources:
  - name: search
    type: opensearch
    connection:
      host: 127.0.0.1
      port: 9201
  - name: content
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5431
      username: postgres
      password: changeme
      database: postgres
  - name: staging
    type: postgres
    connection:
      host: 127.0.0.1
      port: 5430
      username: postgres
      password: changeme
      database: postgres

metrics:
  - name: count_search
    data_source: search
    type: document_count
    properties:
      indices:
        - index_1
    filter:
      search_query: '{"query" : {"term" : { "user.id" : "kimchy" }}}'
  - name: count_content
    data_source: content
    type: row_count
    properties:
      tables:
        - table_1
    filter:
      sql_query: 'category == 1 AND is_valid is True'
  - name: count_staging
    data_source: staging
    type: row_count
    properties:
      tables:
        - table_2
    filter:
      sql_query: 'category == 2 AND is_valid is True'
