[tool.poetry]
name = "datachecks"
version = "0.1.0"
description = ""
authors = [
    "Waterdip Labs <hello@waterdip.ai>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
click = "^8.1.5"
pyyaml = "^6.0"
opensearch-py = "^2.2.0"
sqlalchemy = "^2.0.19"
psycopg2 = "^2.9.6"

[tool.poetry.scripts]
datachecks = "datachecks.cli.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
